version: '3.4'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=http://+:5000
    ports:
      - 8001:5000
      - 5000:5000
    depends_on:
      - database
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8002:80
    depends_on:
      - backend
  database:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itemsdb
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local